# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-07-06 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='email',
            new_name='mail',
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guest',
            name='realname',
            field=models.CharField(max_length=64),
        ),
    ]
